language: php

php: '5.5'

sudo: false

env:
  - WP_VERSION=master WP_MULTISITE=0 PHPLINT=1

matrix:
  include:
    - php: '5.6'
      env: WP_VERSION=master WP_MULTISITE=0 PHPLINT=1 COVERAGE=1
    - php: '5.2'
      env: WP_VERSION=master WP_MULTISITE=1 PHPLINT=1
    - php: '5.6'
      env: WP_VERSION=4.1 WP_MULTISITE=1
    - php: '5.5'
      env: WP_VERSION=master WP_MULTISITE=0
    - php: '5.5'
      env: WP_VERSION=4.1 WP_MULTISITE=1
    - php: '5.4'
      env: WP_VERSION=4.1 WP_MULTISITE=0
    - php: '5.4'
      env: WP_VERSION=4.1 WP_MULTISITE=1
    - php: '5.5'
      env: WP_VERSION=4.1 WP_MULTISITE=0
    - php: '5.5'
      env: WP_VERSION=4.0 WP_MULTISITE=1
    - php: '5.3'
      env: WP_VERSION=4.0 WP_MULTISITE=0
    - php: '5.4'
      env: WP_VERSION=3.9 WP_MULTISITE=0
    - php: 'hhvm'
      env: WP_VERSION=4.1 WP_MULTISITE=0
    - php: 'hhvm'
      env: WP_VERSION=4.1 WP_MULTISITE=1

before_script:
  - phpenv local 5.6
  - composer selfupdate 1.0.0-alpha10 --no-interaction
  - composer install --no-interaction
  - composer config-yoastcs
  - phpenv local --unset
  - PLUGIN_SLUG=$(basename $(pwd))
  - export WP_DEVELOP_DIR=/tmp/wordpress/
  - git clone --depth=50 --branch="$WP_VERSION" git://develop.git.wordpress.org/ /tmp/wordpress
  - cd ..
  - cp -r "$PLUGIN_SLUG" "/tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG"
  - cd /tmp/wordpress/
  - cp wp-tests-config-sample.php wp-tests-config.php
  - sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
  - sed -i "s/yourusernamehere/travis/" wp-tests-config.php
  - sed -i "s/yourpasswordhere//" wp-tests-config.php
  - mysql -e "CREATE DATABASE wordpress_tests;" -uroot
  - cd "/tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG"
  - phpenv rehash

script:
  - if [[ "$PHPLINT" == "1" ]]; then find -L .  -path ./vendor -prune -o -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l; fi
  - if [[ "$PHPLINT" == "1" ]]; then vendor/bin/phpcs -v; fi
  - if [[ "$COVERAGE" == "1" ]]; then phpunit -c phpunit.xml --verbose --debug --coverage-clover build/logs/clover.xml; else phpunit -c phpunit.xml; fi
  - if [[ "$COVERAGE" == "1" ]]; then sed -i -e 's/tmp\/wordpress\/src\/wp-content\/plugins\///g' build/logs/clover.xml && vendor/bin/test-reporter; fi

notifications:
  slack:
    secure: 1sg/MwkvRDNLgOxkQ6lvDRGgKbNt0gpwYN6bgGxcT3hOxPMJjjNBJlwO6td/3NuMuMjr/EomzXprL8XOlqPsyBfqFZoLX+fV3v4or2IVyUjPdQVStOX1UsV9kTAIW81idSoGarvRV/PAN1HHfHc+wuLTqpSSPhrtxuGxNozvvl0=
  email: false

addons:
    code_climate:
        repo_token: 66e7142d58a1f56c618ae913f69b6ada1e6c859ed5dc8627f71e7c7518b55f59
